import type { Metadata } from 'next';
import Script from 'next/script';
import { Html, Head, Main, NextScript } from "next/document";

export const metadata: Metadata = {
  title: "마니마니또",
  description: "Generated by Sangyeon",
  icons: {
    icon: "../public/logo.png"
  },
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Script
          src="https://developers.kakao.com/sdk/js/kakao.js"
          strategy="afterInteractive"
        />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
